### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by mills1975** [emcniece/ha_imap_attachment#11]
Hello,

I've got a problem... cant get Imap_attachment to work... according to the log, I encounter a Type Error:

**Log:**
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 573, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 993, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ha_imap_attachment/sensor.py", line 292, in update
    message = self.render_template(email_message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ha_imap_attachment/sensor.py", line 200, in render_template
    ATTR_ATTACHMENT_PATHS: EmailContentSensor.get_msg_attachments(email_message, self._storage_path),
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ha_imap_attachment/sensor.py", line 272, in get_msg_attachments
    fullpath = os.path.join(storage_path, filename)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 90, in join
  File "<frozen genericpath>", line 152, in _check_arg_types
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

**My configuration:**
- platform: imap_attachment
    name: LINZ NETZ Attachments
    server: **********
    port: 993
    folder: VDI
    senders:
        - co******@*******.at
    username: ****@********.at
    password: ********************
    storage_path: "/config/attachments"
    value_template: "{{ ( attachment_paths | select('search', '.csv')) | first | default('unavailable') }}"

Hope someone has a solution for my problem... Thanks in advance!

**Comment by emcniece** [comment]
Looks like the problem is `os.path.join(storage_path, filename)`, and I see you have already defined `storage_path: "/config/attachments"` so it may be that `filename` is set to `None`.

`filename` is set here: https://github.com/emcniece/ha_imap_attachment/blob/master/sensor.py#L271

Does your attachment have a valid filename? Even if it does, this might be the problem: https://stackoverflow.com/questions/6429406/get-filename-from-email-attachment-in-python

Needs inspection, testing, and probably a fix. I'll keep this in mind, though my time is limited at the moment. Thank you for the report!

**Comment by thomasgebets** [comment]
Had a simiar issue and adapted the function like this to make it work:

`
@staticmethod
    def get_msg_attachments(email_message, storage_path):
        attachments_saved = []

        for part in email_message.walk():
            if part.get_content_maintype() == 'multipart':
                continue

            # Get the filename
            filename = part.get_filename()
            if filename is None:
                _LOGGER.debug("Skipping file with a None-Filename %s", filename)
                continue
            _LOGGER.debug("Attachment filename: %s", filename)

            # Get the attachment payload
            payload = part.get_payload(decode=True)
            if payload is None:
                _LOGGER.debug("Skipping attachment with empty payload: %s", filename)
                continue

            # Ensure storage path exists
            os.makedirs(storage_path, exist_ok=True)

            # Save the file
            fullpath = os.path.join(storage_path, filename)
            with open(fullpath, 'wb') as f:
                f.write(payload)

            _LOGGER.debug("Saved attachment to: %s", fullpath)
            attachments_saved.append(fullpath)

        return attachments_saved
`
